#!/bin/bash
#
# Based in algorithim of project [ easyLife Vers.4.6 by duli ]
#    easyLife - Automated software install and configuration for Fedora.
#    Copyright (C) 2017  Luis Felipe B. Marzagão (duli)
#
# This version is the project [ lNoob Vers.20.04.a by ELO-Edson ]
#    Copyright (C) 2020  Edson Leonel de Oliveira (ELO)
#
#	lNoob is a free software to redistribute, modify and rewrite without
#   lost the history of producers. I put it under the terms of the
#   GNU General Public License as published by the Free Software Foundation,
#   either version 3 of the License, or (at your option) any later version.
#   (can see more in COPYRIGHT file)
#   A oroginal copyright can be found, see <http://www.gnu.org/licenses/>.
#
# Define variables to [ en ]
VERSION="20.04.a"
LOGFILE="/var/log/easylife.log"

echo -e '███╗ ███╗   ██╗'
echo -e ' ██║ ████╗  ██║ ██████╗  ██████╗ ██╗'
echo -e ' ██║ ██╔██╗ ██║██║   ██║██║   ██║██████╗'
echo -e ' ██║ ██║╚██╗██║██║   ██║██║   ██║██   ██╗'
echo -e ' ███╗██║ ╚████║╚██████╔╝╚██████╔╝██████╔╝'
echo -e ''
echo -e "\nlNoob - Copyright (C) 2020  Edson Leonel de Oliveira (ELO)"
echo -e "Version: $VERSION"
echo -e "\nThis program comes with ABSOLUTELY NO WARRANTY."
echo -e "lNoob is free software, and you are welcome to redistribute it"
echo -e "under conditions in the file LICENSE for details.\n"
echo -e "\n"

# Discover easylife installation folder and actual to return
export RUNDIR=$(dirname "$0")
export EXITDIR="$pwd"
cd "$RUNDIR"

# define language default ro en_US if not exist translate to default language
defLang="${LANG%%.*}"
defLang="${defLang:-en_US}"
[[ -f lang/"${EL_LANG}.sh" ]] && source lang/"${EL_LANG}.sh" ||	source lang/en_US.sh


# Source all scripts, functions etc.
for src in lib/common/*.sh; do source "$src"; done

for src in lib/*.sh; do source "$src"; done


# Make sure zenity is installed (not really necessary if zenity is listed as required at SPEC file)
#ZenityOn || Terminate


# Change zenity's default behavior on focus_on_map property, so dialog boxes appear in the front
# https://bugzilla.redhat.com/show_bug.cgi?id=479394
#sed -i '/<property name="focus_on_map">False</s/False/True/' /usr/share/zenity/zenity.ui




# Kill previous dnf still running
pkill -SIGKILL -u root -o dnf


# Run required verifications
IsRoot || Terminate

# Use much safer method --disableplugin=refresh-packagekit instead
#RefreshPackagekitOff || Terminate

WhichUser || Terminate

# Show notification icon - after WhichUser because then we will have $USERNAME
#sudo -u "$USERNAME" zenity --notification --window-icon="/usr/share/pixmaps/easylife.png" --text "$COMMON_MSG_ELNOTFICATION" &

RpmfusionOn || Terminate

FreshrpmsOff

#AtrpmsInstall

pkill -SIGKILL -u root -o dnf

# Get setup/install options 
GetOpt

# Populate an array with selected functions from GetOpt (PS: substituting "|" with "")
FUNCTIONS=(${SELECTION//|/})

# Exit if no selection is made
[[ -z "${FUNCTIONS[*]}" ]] && Terminate


# Cleanning yum headers and stuff seems to prevent download erros
# yum clean headers metadata dbcache


# Get download urls or exit
GetDlUrls || Terminate


# Run selected functions and log them to a logfile
# TODO: Implement "logger -p local0.info -f $LOGFILE -t info "Msg here..."
for GO in ${FUNCTIONS[@]}; do
	#echo -e "\n$(date +%c) - easyLife version: $VERSION\n" | tee -a "$LOGFILE"
	#"$GO" | tee -a "$LOGFILE"
	"$GO"
done


# End program
Terminate
