#!/bin/bash
#
# Based in algorithim of project [ easyLife Vers.4.6 by duli ]
#    easyLife - Automated software install and configuration for Fedora.
#    Copyright (C) 2017  Luis Felipe B. Marzagão (duli)
#
# This pkgVersion is the project [ lNoob Vers.20.04.a by ELO-Edson ]
#    Copyright (C) 2020  Edson Leonel de Oliveira (ELO)
#
#	lNoob is a free software to redistribute, modify and rewrite without
#   lost the history of producers. I put it under the terms of the
#   GNU General Public License as published by the Free Software Foundation,
#   either pkgVersion 3 of the License, or (at your option) any later pkgVersion.
#   (can see more in COPYRIGHT file)
#   A oroginal copyright can be found, see <http://www.gnu.org/licenses/>.
#
# Dependences
#	zenity
#
# Starting configuration
pkgVersion="20.04.a"
logFile="/var/log/easylife.log"

echo -e '███╗ ███╗   ██╗'
echo -e ' ██║ ████╗  ██║ ██████╗  ██████╗ ██╗'
echo -e ' ██║ ██╔██╗ ██║██║   ██║██║   ██║██████╗'
echo -e ' ██║ ██║╚██╗██║██║   ██║██║   ██║██   ██╗'
echo -e ' ███╗██║ ╚████║╚██████╔╝╚██████╔╝██████╔╝'
echo -e ''
echo -e "\nlNoob - Copyright (C) 2020  Edson Leonel de Oliveira (ELO)"
echo -e "pkgVersion: $pkgVersion"
echo -e "\nThis program comes with ABSOLUTELY NO WARRANTY."
echo -e "lNoob is free software, and you are welcome to redistribute it"
echo -e "under conditions in the file LICENSE for details.\n"
echo -e "\n"

# Discover easylife installation folder and actual to return
export RUNDIR=$(dirname "$0")
export EXITDIR="$pwd"
cd "$RUNDIR"

# define language default to en_US if not default language system
defLang="${LANG%%.*}"
defLang="${defLang:-en_US}"

# Charge defined language variables
[[ -f lang/"${defLang}.sh" ]] && source lang/"${defLang}.sh" ||	source lang/en_US.sh

# Charge all system scripts and funcions
for src in lib/*.sh; do source "$src"; done

# Make sure zenity, if not, call to install
#ZenityOn || Terminate


# Change zenity's default behavior on focus_on_map property, so dialog boxes appear in the front
# https://bugzilla.redhat.com/show_bug.cgi?id=479394
#sed -i '/<property name="focus_on_map">False</s/False/True/' /usr/share/zenity/zenity.ui




# Kill previous dnf still running
pkill -SIGKILL -u root -o dnf


# Run required verifications
IsRoot || Terminate

# Use much safer method --disableplugin=refresh-packagekit instead
#RefreshPackagekitOff || Terminate

WhichUser || Terminate

# Show notification icon - after WhichUser because then we will have $USERNAME
#sudo -u "$USERNAME" zenity --notification --window-icon="/usr/share/pixmaps/easylife.png" --text "$COMMON_MSG_ELNOTFICATION" &

RpmfusionOn || Terminate

FreshrpmsOff

#AtrpmsInstall

pkill -SIGKILL -u root -o dnf

# Get setup/install options 
GetOpt

# Populate an array with selected functions from GetOpt (PS: substituting "|" with "")
FUNCTIONS=(${SELECTION//|/})

# Exit if no selection is made
[[ -z "${FUNCTIONS[*]}" ]] && Terminate


# Cleanning yum headers and stuff seems to prevent download erros
# yum clean headers metadata dbcache


# Get download urls or exit
GetDlUrls || Terminate


# Run selected functions and log them to a logfile
# TODO: Implement "logger -p local0.info -f $logFile -t info "Msg here..."
for GO in ${FUNCTIONS[@]}; do
	#echo -e "\n$(date +%c) - easyLife pkgVersion: 
	pkgVersion\n" | tee -a "$logFile"
	#"$GO" | tee -a "$logFile"
	"$GO"
done


# End program
Terminate
